// import type { Metadata } from "next";
// import { Inter } from "next/font/google";

// import "./globals.css";
import Header from "@/components/Header";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex justify-center items-center min-h-[300px]">
          <div className="w-16 h-16 border-4 border-t-4 border-purple-600 border-solid rounded-full animate-spin"></div>
        </div>

        <div className="w-full absolute top-0">
          <Header />
        </div>
        <div className="absolute sm:top-[8%] top-[9%] w-full h-[90vh]">
          {children}
        </div>
      </body>
    </html>
  );
}
